(ns advent-of-code-2020.day-3-test
  (:require [clojure.test :refer :all])
  (:require [advent-of-code-2020.day-3 :refer :all]))

(def day-3-sample
  [[false false true true false false false false false false false]
   [true false false false true false false false true false false]
   [false true false false false false true false false true false]
   [false false true false true false false false true false true]
   [false true false false false true true false false true false]
   [false false true false true true false false false false false]
   [false true false true false true false false false false true]
   [false true false false false false false false false false true]
   [true false true true false false false true false false false]
   [true false false false true true false false false false true]
   [false true false false true false false false true false true]])

(deftest day-3-sample-test
  (testing "day-3-1"
    (is (= 7
           (day-3-1 day-3-sample 3 1))))

  (testing "day-3-2"
    (is (= 336
           (day-3-2 day-3-sample [[1 1] [3 1] [5 1] [7 1] [1 2]])))))

(def day-3-input
  [[false true true false false false false false true false false false false true false false false false true false false true false true false false false true false true true]
   [false true true true false false false false false false false false true false true true false false false false true false false false false false false true false false true]
   [true false false true false false true false false false false false true false false false true false false false false true false true false false false false false false false]
   [false false false false false false false false false true false false false false false false false false false false false false false false false false false true false false false]
   [false false true false false false false false false false true false true false false false false false false false true false false false false false false false true false true]
   [false true true true true false false false false false false false false true false true false false true true false false false false false false false false false true false]
   [false false false false false false false false true false false false false false false false false false true false false false false false false false false false true false false]
   [true false false true true false false false true true false false false false true false false false false false true true false false false false false false true false false]
   [false false false false false false false false false true false false false false false false false false false false false false false false true false false false false false false]
   [true false false false false false false false false false true false false false true true false false false false false false false false false true false true false false false]
   [false false false false false false false false false false false false false false true false false false false false false false false true true false false false false false true]
   [true true false false false false true false false false false false false false false false false false true false false false false true false true false false false true false]
   [false false false false false true false false true false false false false false true false false false true false true false false false false false false false false false false]
   [true false false false false false false false true false false false true false false true true false false false false false false false false true true false false true false]
   [false true false false false false false false false false true false false false false false false false true false false false false false false false false false false false false]
   [false false false false false false false true true false false false false false true false true false true false false true false true false false false false false false false]
   [false false true false false false false false false true false false true false false false false true true false false false false false false true false true false false false]
   [false false false false false true true false false false false true false false true false false false false false true false false true false false false false false false false]
   [false false false false false false false false false false false false false true false false false false false false false true false true false false false false true false false]
   [false false false false false false false false false false false false false false false false false true false true false false false false false false true false false false false]
   [false true false false true false false false false true false false false false false false false false false false true false false false false false true false true true false]
   [true false true false true false true false false false false false true true true false false false false false false false true false false false false false true false false]
   [true false false false true false false false false false false false false false false true false false true false false false false false false false false false false false false]
   [false false false true false false false true true false false false false false false false true false true true false false true false false false false false false false false]
   [false false true false false false true false true false true true false false false true true false false false false false false false false false true false true false true]
   [false false false false false true false false false true false true false false false false true false true false false false false false true false false false false false false]
   [false false false true false false false true false true false false true false false false true false false false false false true false false false false false false false false]
   [false false false false false false false false false false false true true true false true false false false false false false false true false true false false false false false]
   [false false true false false true false true false false false false false false false false true false true false false false false false false false true false true false true]
   [false true false false false false false false false true false false false false false false false false false false false true false false false false false false false false false]
   [false true false false true false false false true true false false false false true false false false false false false false true true true false false true true false false]
   [true false false false false true false false false false false true false false false false true true false false true false false false false false false false false false true]
   [true false false true false false false false false false false true false false false true false false false false false false true false true false false false false true false]
   [false false false false false false true true false false true false false true false false false false true false true false false false false false false false false true true]
   [true false false false false false true false false false false false false false false false true false false false false false false true false false true true false false true]
   [false true false false true false false false false false false false true false false false false true false false false false false false false false false false false false true]
   [false false false false true false false false false false false false false false false true false true false false false true true false false false false true false true true]
   [false false true false false false true false true false false false true false true true true false true false false true false false false false false false true false false]
   [true false true false false false true false false false false false false false false false false false false false false true false false false false false false false true false]
   [false false true true false false false false false false false true false false false false false false true false false false false true true true false false false false false]
   [false false false false false false true false false false false false false false true false true false true true false true false false true true false true false false false]
   [false true false false false false false false true false false false false false false true false true false false false false true false false true false true false false true]
   [false false false false true false false false false true false false true false false false true false false false false false true false true false false true false false false]
   [false true false false false false false true false true false true false false true false false false false false false false false true false true false true true true false]
   [true false false true false false true false true false false false false false false true false false true false false true false false false false true false true false false]
   [false false true false true true true false false false false true false false false false true true false false false true false false false false false false false false false]
   [false false false false false false false false false false false true false false true false false false false false false false false false false false true false false false false]
   [false false false false false false false false false false false false false false false false false true false false false false false false false false false false true false true]
   [false true false true false false false false true false false true false false false false false false false false true false false true false false false false false false false]
   [false false false false false false false false false false false true true false false true false false false false false false false false false false false false false false false]
   [false false false true false true true false false false false false false false false false true false false false false false false false false false true false true false true]
   [false false false false false false false false true false false true false false false false true false true false false false false false false false false false false false false]
   [false false false true true false false false true true false false false false false false false false false false false false false false false false false false true false true]
   [false false false true false false true true false false true false false false true false false false false false false true false false false false false true false false true]
   [false true true false true false false true false false true false false false false false false true false false false false false false true false false false false false true]
   [false false false false true false false false false false true false false false false true false false false false false false true true false true false false false false false]
   [false false false false false true false true true false false false false true false false false true false false false false false false false false false false false false false]
   [false false false false false false true false false false true false false false false false true true false false false false true false false false true false false true true]
   [false false false true false false false false false false false false false false false false true false true true true false false false false true true false false false false]
   [false false false false false false false false false false false false true false true false true false false false true false true false false false false false false false false]
   [true false false false false false true false false true false true false false true true false false false false false false false false false false false true false true true]
   [false false false false false true false true false true false true false false true true false false false false false false true true false true false false true false false]
   [false true false true true false false true false false false false false false false false false true false false false false false false true false false false false false true]
   [false true false true false true false true false true false false true false false true false false false false false false false false true true true false false false false]
   [false false false false false false true true false false false false false false false false false false true false true false false false false false true true false false true]
   [false false true false false false true false false true false false false false false true false true false false false false false true false false false false false false false]
   [false false false false false false false false false false false false true false false false false true false false false false false false false false false false false false false]
   [false false false false false false false false true false false false true false false true false false false false true false true false false true true true false false false]
   [true false false false false false false false false true true false false false false true true false false false false false false false false false false false false false false]
   [false false false false false false false false false true false true false true false false true false false true false false false true false true false false false false false]
   [false false false false true false false false false false false false false false false false false true false false false false true true true true false false false true false]
   [true true false true false true false false false false false false true false false false false false true false false false true false false false false true true true false]
   [false false false true false false true false false true false false true false false false false false false false true false false true false true false true false false true]
   [false false true false false true false false false false true false false false true false true true false false true false false false false false false false false false true]
   [true false false true false true false false false false true false false false false true false false false true false false true true false false true false true false false]
   [false false false true false false false false true false false false false false false false false false false false false false true false false true false true false false true]
   [false false true false false false false false false true false true true false false false true false false false false false false false false false false false false false false]
   [true false false false false true true false true false true false false false true true false false false false false false true false false false false false true true false]
   [false true false false false true true false false false true false false false true true true true false false false false false true true false false false false false false]
   [false false false false false false false false false false false true false true true true false false false false true false false false true false false false true false false]
   [true true false false true false false true true false false true false false true false true false true false false true true true false false false false false false false]
   [false true false false false true true false false false false false false true false false false false false false false false true true false false true false false false false]
   [false true false false false true false false false true false false false false false true false false false false false false false false false false false false true false false]
   [false true false true false true false false false true false true false false true false false false false false false false true false false false false false false true false]
   [false false false false false false false false false false false false false false false false false true false false true false true false false false false false false true false]
   [true false false true true true true true false false false false false false true true false true false false false false true false false false true false false false false]
   [false false false false false false false false true false false false false false false true false false false false false true true false false false false false false true false]
   [false false false false true false true false false false true false false false true false false true false false false false false false false true true true true true false]
   [false false false false false true true false false false false false false true false false false true false false false false false false false true false false false false true]
   [false true false false false false true false false false true false false true false false false true false true false false false true false false true false false false true]
   [false false false false true true false false false false false false false false false true false true false false false true true true true false true false false false false]
   [false false false true true false false false false false false false false false false true false true false false false false false false false true true false false false false]
   [false false false false false false false false false true false false false false false false true false false false false false true false false false false true false false false]
   [true false false false false true true false false true false false false false false false true false false false false false true true false false false false true false false]
   [false false false true false true false false false false false false false false false false false false false true false false false true false false false false false true false]
   [false false false false false false false false false false false true false false false true false true false false false false true false false true false true false false false]
   [false false false false false false false true false true false true false false false false false true false false true false false false false false false false false true false]
   [false false true true false false false false false true false false true false false false false false true true false false true false false false false false false false false]
   [false false false true false true false false false false false false false false false false true false false false true false false false false true false true false false false]
   [false false true false false false false true false false false false false false true false false false true false true false false false true true false false true false true]
   [false true false false false true false false true false false true false false true false false false false false false false true false false false false false false false false]
   [false false false false false false false false false false false false false false false false false true false true false false false false false false false false false false false]
   [false false false false false false false false false false false false false false false true false false false false false false true true false false false false false true false]
   [false false true true false false false false false true true true false false true false false false false true false false false false false false false false false true true]
   [false false false false true false true false false false false false false false false true false true true true true false true false false false true false false false false]
   [false false false false false true false false false false false true true false false true true true true false false true true false false false false false false false true]
   [false false false false false true true true true false true false false false true false false false false false false true false false false false false false false false false]
   [false false false false false false false false true false false true false false false false false false true false false false false false true true false false false false false]
   [false false false true true true false false true false true false false true true true false false false false false false false true false false false false false false false]
   [false false false true false false false true true false false true false false true false false true false false true false true true false false false false false false false]
   [false false true false false false false false false true true false false true false false false false false true true false false true true false false false false false false]
   [true false false false false false false false true false true false false true false false false false false false false false false false false false false false false false false]
   [true false false false false false false false true false false false true false false true true true false false false false true false true false true false true false false]
   [true false false false true false true false false false false true true false true true false true false false false false false false false false false false false true false]
   [false true false false false false false false false false false true false false true true true false false true false false false false false false false false false true false]
   [true false false false true false false false false false false true false false false true false true false false false false false false false false false true false false false]
   [false true false true true false false false false false false false false false false false false false false true false true false false false false true false false false true]
   [false false false false false false false false true false false false false false true false false true false true false true false false false false false false true false false]
   [false false false false false false false false false false false false true true true true false true false false false false false false true false false false false false false]
   [false false false false false false true false true false true false false false true false true false false false true false true false false false false false true false false]
   [false false false false true false false false false true false false false true false false false false false true false false false false false false false true false true false]
   [false false true false false false false true false false false false true true true false false true false false false false true false false false false false true true false]
   [false false false false false false false false false false false false false false false false false true false false false false false true false true false false false false true]
   [false true false false false false false false false false false false false false false true false false false false false false true false true true false false true false false]
   [true false false false false false true true false false false false false false false true false false true false false false false false true false false false false true false]
   [true false true false false false false false false true true true true false false false true true false false false false false true false false false false true true false]
   [false false false false false true false true false false false false true false false false false false false false false false false false false false false false false false false]
   [false false false false true false false false false true false false true false true false false false false false false false false false false false true true false false false]
   [false false false true false false false false false false false false false false false false false true true false false false false false false true false false true false false]
   [false false false false false false true false false false false false false false false false false true false false false true false false false true true false true true true]
   [false false false true true false false false false false false true true false false false false false true false false false false false false true false false false false true]
   [false false false false false false false false true false true false true false false false true false false false true false false true true false false false false false false]
   [false false false false false false false false false false false false false false false false false false false false false false true true true false false false false true true]
   [false true false false false false false true false false true false false true false true true false true false true false true false false false false true false true true]
   [false true false false false false false false false false false false false false false false true false false false false false true false false false false false false true false]
   [false true false false false true false true true false false false false true false false false false false true false true false true false false true false false true false]
   [true true false false false true true false false false false false false false true false false false false false true false false true true true false false false false false]
   [false false false true false false true false true false false false false true false false false false false false false false true false false false false false false false false]
   [false false false false true false false false false false false false false false false false false false false true true false false false true false false false false false false]
   [false false false false false false false false false false false true false false true false false false false false true true false true false true false true false false false]
   [true false true false false false false false true true false false true true false true false true false false false false false false false false true false false false false]
   [false false false false false false false false false true false false false false true false false false false false true false false true true false true false false false true]
   [false false false true false false false true false false true false false true false true true true true false false false true false false false false false false false true]
   [false false false false false true true false false false false false true true false false false false false true false false false false false false true false false false false]
   [true false true true false false false true false false false false true false false false false false false false false false false false false true false false true true false]
   [false true false true true false false true false false false true false false false false true false true false false false false false false true false false false false false]
   [false false true true true false false false false false false false false false false false false false false false false true false false false false false false false false false]
   [false true false false true false false true false false false false false false false false false false false false false false false false true false false false false false false]
   [false false false false true false false true false false false false false false false false true false false true false false false false true false false false false false false]
   [false true false false false false false false false false false false true true true false false false false false false true false false false true true true false false false]
   [false false false false false false false false false false false true true false false false true false true false false true false false false false false false false false false]
   [false false false true false false false false true false false false false false false false false false false true false false false false false true false false true true false]
   [false false true false false true false false false false false false false false false false false false false true false false false false false false true true true false false]
   [true false false false false true false false false false true true false false false false false true false false false false true false true true false false false false false]
   [false false false false false false true false false false false false false false true false false true false false false false false false false false false false true true false]
   [true false false true true false true false false false true false true false false false false false false false false false true false false false false true false true false]
   [false false false true false false false true false false false false false false false false false false true false false false true false false true false false false false true]
   [false false false true true true false false true false true false false false false false false true false true true false true true true true true false false false true]
   [false false true false false false false false true false true false false false false false false false false false false false false false false true false false true true false]
   [true false false true true true false false false false false false true false true false false true false false false false false false false false true false false false false]
   [false true false false false false false false false true false false false false false false false true false false false false false true false true true false false false false]
   [false true false false false true true false false true false false false false false false false true true false false false false false true false false false false true true]
   [false false false false false false false false false false true false true false false true false false false false false true false false false false false false false false false]
   [false false false false false false false true true true true false false false true false false false true false false false false false true true false false false false false]
   [false false false false false false true false false false false false false false true false false false false false false false true false false true false true false false false]
   [false false false true true false false false false true true false true false false false false false false false true false true true false false false false false false true]
   [false true false false false true false false false false false false false false false false false false true false false false false false false true true false false false false]
   [true false false true false false true false false false true false true false false false false false false false false true false false false false false false false false false]
   [false false false false false false false true false false false false false false false true false false false false false true true false true false false false false false false]
   [false true false false false false true true false false false true false false false false true false false false false false false false false false true false false false true]
   [true false true false false false false true false false false false false true true false false false false false false false false false false false true false false true false]
   [false false false false false true false false false false false false true false false false false true false false false false false false true false true false false false true]
   [false true false false false false false false false false false false false false true false false false true false true false false false false true false false false false true]
   [false false false false false false false false true true false false true false false true true false false true true false true true false false false false true false false]
   [false false false false false false false false false false false false false false false false false false false false false false false false true false true false false false false]
   [true false false false false true false false false true false false false false false false false false false false false false false false false false false false false false false]
   [true true false true false false false false false false false false false false false false false true false false false false false true false false false true true false true]
   [false false false false true true false false false false true true true false false false false false false false true false false false false false false false false false false]
   [false false true false true false false true false true false false false true true true true false false false false false true false false false false false true false false]
   [true false false false false false false false false false true false false false false false false false true false false false false false false true false false true true false]
   [false true false true false false false false false false false false false false false false false true false false true false false false true false false false true false false]
   [true false false true false false false false true false false false false true false false true true false false false false false false false false false true false false false]
   [true false true false false false false false true false true true false true false false false true false true true false false true false true false false true true false]
   [false false false false false false true false false false false false false true false true true true false false false false true false false true true true false false false]
   [false true true false false false true false false false false false false false true false false false false false false false false false true false true false false false true]
   [false false false false false false false false false false true false false false true false false false false true false false true false false false false true false false false]
   [false false false false false true false false false true false false false false false true false false false false true true false false false false true false true false false]
   [true false false false false true false false false false false false false false false false false true false true false false false true false false false false false false false]
   [false true true true false false true false false false false false false false false true true false false false false false false false false false false true false false false]
   [false false false false true true true false true true false false true false false false true false true false false true true false false false false false false true true]
   [false true false false false true false false false false false false false false false false false true false false false false false false false false false false false true false]
   [true false false false false false false true false false false false true false true true false false false false false false false false false true true false false true false]
   [false true false false false false false false false true false false false false false false false false true false false false false false false true false true false true false]
   [false false false false false false false true false false true true false false false false false false false false false true false false false false false false true false false]
   [false true false false true false false false false false true true false false false false true true false false false false true false false false false false true false false]
   [true false true false true false false false false false true false false false true false false false false false false true false false false false false false false false false]
   [false false false false false false false false false false false false false false true false true false false false false false false false false false true false true false false]
   [false false false false true false false false true false false false false false false false false false false false false false true false true false false false false false false]
   [false false true true false true false false false false false false false false false false false false true false true false true true false false false false true false false]
   [false false false false false true true true true false false false false false false false false false false true false true false false false false true true false false true]
   [false false false false false false true false true false false false false false false false false false true false false false false false false false true true true false false]
   [true false false false false true true false true false false false true false true false false false false false false false false false false false true false false false true]
   [false false false false false true false false false true false false false false false false true false false false false true true true false false false true false false true]
   [true false false false false true false false false false false false false false false false false false false false true false false false true false false false false false false]
   [false false false true false false true true true false false false true false false false false false false false false false false true false false false false true false false]
   [true false false false false false false true false false true false true false true false false false false false false true false false true false false false true false false]
   [false false false false false false false false false false false false false false false false true true false false false false false false true false false true false false false]
   [false false false false true false false true false false true false false false false false false false false true true false false true false false false true false false false]
   [false false false true true false false false false false false false true false true true false true false false false false false true true false false false true false true]
   [false false false false false false false true false true true false true false false true false false false false false true false false false true false false false false false]
   [false false false false false false true false false false false false false false false true false false true false false false false false false true true false true true false]
   [false false false false false false false false false false false false false false false false false false false false true false false false false false true false true false false]
   [false true true false false false false true false false false true false false false true true false false false true false false false false false false false false false true]
   [false false true false false false true false false true false true true false false true false true false true false false false false false false true false false false false]
   [true false false false false true true true false true false false true false false true false false false true false false true false false false true true false false false]
   [true false false false false false false false true false false false false false true false true false false false false false false false true true true false true false true]
   [false true false true true false false false true true false false true false false false false false false true false false false false true false false false true false false]
   [true false false false false false true false false false false false false false true true false false true false false false false true false false false false false false false]
   [false false false true true true false false false true false false false false false false false false false false false false true false false false false true false false true]
   [false true false false false false true false true false false false true false false true false false true false true true false true false true false true false false false]
   [true false false false false false false true false true false false true false true false true false false false false false false true false false false false false false false]
   [false false true false false true false false false false true true true false true false false false false false false false false true false false true false true false false]
   [false false false false false false false true false false false false false false true true false false false false false false false false false true false false false false false]
   [false false false true false false false true true true false false true false false true false true true false true false false true true false false false false false false]
   [false true false false false false false false false true true false false false false false false false true false false true false false true false true true true false true]
   [false true true true false true false false true false true true true false false false false false false false false false false false true false false false false false false]
   [false false false true false false false false false false false false false false false false false false false false true false true false false false true true false false true]
   [false false false false true false true true true false false false false true false false false false false false false true false false false false false false false false true]
   [false true true false false false true false false false true false false true false false false false false true false false false true false false false false false false false]
   [false true false false false true false false true false false false false false false false false false false false true false true false false false false false false true true]
   [false false false true true false false true false true false true false false true false true false true false false false false false false false true false false false false]
   [false true false true false false true false false true false true false false false false false false false false false false false true false false false false false false false]
   [false false true false false false false true false true false true false true false true false false false false false false false false false false false false false false true]
   [false false true true false false false false false false false false false false false false false false true true false false false false true false true false false true false]
   [false false true false false false false true false false false true true false false false false false true true true false false false false false true false true false true]
   [true false false false false true false false false false false false true false false false false false false false false false false true true false false false false false false]
   [false true true false true false true false false false false false false true false false false true true false false true true true false false true false false false false]
   [false true false false false false false false false false false false false true false true true false false false false false false false true true false false true true false]
   [true true true false false false false false true true false false false true false true true false false true false false false false false false false false false false false]
   [false false false true false false false false false true false false false false false false false false false false false true false false true false false false false false true]
   [true false false false false false false false false false true false false false false true false false false false false false false true false false false false false false false]
   [false true false true false false false true false true true true false false false false true false false true false false false false false false false false false false false]
   [false false false false false true false false false false false false false true false false false false false true false true true false true false true false true false false]
   [false false true true false true false false false false false false false false false true true false false false false false false false false false true false false true false]
   [false false false false false false false true false false false false true false false false false false false true false false false false false false false false false true true]
   [false false false true true false false false false false true false false true false false false false false false false true false false true false true false false false false]
   [false false true false false false true true true false false false false false false false true false false true false false false false true true true false false false false]
   [false false false false false false false true false false false true true true false false false false false false true false true false false false false false true false true]
   [true false false false false true false false false true false true false false false false true false true false false false false false false false false false false true false]
   [false false false false false false false false true false false true false false false false false true false true false true false false false false false false false false false]
   [false false false false false false true true false false false false false false false true true true false false false false false false false true false false false true false]
   [false false false false false false false false false true false false true false false true false false false false false false false true false false false false false false false]
   [true false false false false false false false true false false false true false false false false false true false true false false true false false false false true false false]
   [false true true false false false false true false false true true true false false false false false false false false false false false false false true false false false false]
   [true false true false false false true false false false false false false false true false false false false false true true false true false true false false false false true]
   [false false false false true false false false false true true false true false false false false false false false false true true false false false false false false false false]
   [false false false true true false false false true false true false false false false false false false false false false false false false true false false false true true false]
   [true true false false false false true false false false false false true false false true false false true false false false false false false true false false false false false]
   [true false false false true false true false false false false false false false false true true false false false false true true false false false false false false true true]
   [false false true false false false false false false false false false false false true false false true false false false false false false true true true false false false false]
   [false false true true false false true false false false false false true false false false false false false true false false false false true true false false false false false]
   [false false false false true true true false true false false false true false false false false false false true true false false false false false false true false false false]
   [false false false false true false false false false true true true false false false false false false false false false false false true true true false true false false true]
   [false false true false false false false true false false false true false true true false false false false true false false false true false false false false false false false]
   [false false false false true true false false false false false false false false false false false true false false false false false false false false false false false false true]
   [false false true false true false false false false false false true false false false false false false true false true true false true false false false true false false true]
   [true false true true true false false false false false false false false false false false false false true false true false true true false true false false false false false]
   [true false false false false true true false false false false true false false true false true false true false false false false false false false false false false false true]
   [false false false true false false false false false false false false false false false false false false false false false false false true false false false false false false false]
   [false true false false false true false false false false false false true false false false false false false false true false true false false false false true false false true]
   [false false false false true false false false true false false true false false true false false true false true false false false false false true false false false false true]
   [false false true false false false false true false false false false false false false false false false false false true false false true true true false false true true false]
   [false false false true true false false false true false false false false false false false false false false false true false false true false false true false true false false]
   [false false true false false true false false true false false false false false false false false false true false false false false false false false false false true false true]
   [false false false true false true false false false false false true false true false false true true false false false false false false false false false true false false false]
   [false false false false true false false false false false false false false false false false false false false false false false false false false false false false false false false]
   [false false false false true false false false false false true false true false false false true false true true true false false false false false false false false false true]
   [false false false false true false true false false false false false false false true false false true false true false true false false false true false false false true false]
   [false false false false false true false false false true false false true false false false false false true true false false false false true false true false true false false]
   [true false false false false true true true false false false false false false true false false true false false false false false false false false false false true false false]
   [false true false false false false false true false false false false false false true true false false false false false false false true false false false true false true true]
   [false false false true false false true false false false false false true false true false false false false false true false false false false false false false true true false]
   [false false false false false false false false false false false false true false false true false false false false true false false false true false false true false true false]
   [false false false false false false false false false false true false true false false true false false true true false false false false false false false false false false false]
   [false false false false false false false true false false false false false false false true false false true true false false false true true false false false false false true]
   [false false false false true false false false true true false true false false true false false false true false true false false false false false false false true false false]
   [false false false false true false true false false false false false false false false true false false false true true true true false false false true false false false false]
   [true false true false false false false false false false false false false false false false true false false false false false false false false false false false false false true]
   [false true false true false false false false false false true false false false false true false false true false false true false false false false false true true false true]
   [true false false true false false false false false false false false false false false true false false false false false false false false true false false false false false true]
   [true false false false false true false false false false true false true false false true false true false false false false true false true false false false true true false]
   [false false false false true true false false false true true false false false true false false false true false false false false false false false false false false false true]
   [false false false true false true false false true false false false false true false false true false false true false false true false false false false false false false false]
   [false false false true false false true true false false true false false false false false false false false true false false false false false false false false false false true]
   [true false false false false false false true false true true false false true true false false false false false false false true false false true false false false false false]
   [false false true false false false true false false false false false false true false false false true true false true false false false false false false false false false false]
   [false true true true false true false false true false false true false false false false false false false false true true true true false false false true false false false]
   [true false false false false false false false false false false false false false false true false true false true false false false false false false false false true false false]
   [false false true true false false false false true false false false false false false false true false false false false true true false false false true false false true true]
   [false true true false false false true false false true false true false false false false false true false false true false false false false false false false true true false]
   [false false true false false false false false false false false false true true false false false false false false false true false false false false true false false true false]
   [false true false false true false false false true false false true true false true false false true false false false false false true false false false false false false false]
   [false true false false false false true false false false false false false false false false true false false true false false false true false false false true true false false]
   [false false true true true false false true true true true true true false false true false true true false true false false false false true false false false false false]
   [false false false false true false false true false false false false false true false false false false false false false false false false false false false true false false true]
   [false false false true false false false false true false false false false false false false true false false true false true false false false false false false false true true]
   [false false false false false true false false false false false false true false false false false false false false true false false true true false false false true false false]
   [false true true false false true false false false false true true false false true true false false false false false false true false false false true false false true false]
   [false false false false false false true false false false false false false true false false false true false false false true true true false false false false false false false]
   [false false false false true false false false false false true false true true true false false true true false false false false false true false true false true true false]
   [false false false false false false false true false false false false true false false false true false false true false false true false false false true false true false false]
   [false false false true true true true false true false false false true false false false true false true false false false true true false false false false true false false]
   [false false false false false false true false true false false false false true false false false false true false true false false false false true true false false false false]
   [true false false true true false false false false false false false false false false false true true true true false false false false true true false true false false false]
   [false false false true false false false true true false true false false false false false false false true false true false false false false false false false false false false]
   [false false true false false false false false false true false false true false false true false false false true false false false false false false true false false false false]
   [false false true true true false false true false false false false false true false false true false true false false false false false false false true false false false true]
   [true false false false false false false false false true false false false true true false false true false false false true false false false false true false false false false]
   [false false false true false true false false false true false false false false false true false false false false false false false false true false false false true false false]
   [false false false true false false false false true false true true true false false false true false false true false false false true false false true true false true false]
   [false false false false false true false false true false false true false false false true false false false true false false true false false false false false false false false]
   [false false true false false false false false false true true false false false false false false false false false false false false false false false true false true false true]
   [false true false false false true true true false true false false false false true true false false false false false false false false false false true false true false false]])

(deftest day-3-test
  (testing "day-3-1"
    (is (= 223
           (day-3-1 day-3-input 3 1))))
  (testing "day-3-2"
    (is (= 3517401300
           (day-3-2 day-3-input [[1 1] [3 1] [5 1] [7 1] [1 2]])))))
